### ISSUE TITLE
The Great Refactoring

### ISSUE THREAD

**Issue by jlitewski** [Guerra24/Voxel#74]
Progress Report:
- [ ] Core
  - [X] Settings (PR #75) - v0.0.10
  - [ ] Resources
  - [ ] Scripting
- [ ] World (PR #77) (In progress, Mostly implemented by @Guerra24)
  - [x] Client Side render implementations - v0.0.10
  - [x] Dimension (PR #77) - v0.0.10
  - [x] Chunk (PR #77) (Currently debugging) - v0.0.10
  - [x] Block (PR #77) - v0.0.10
- [ ] ECS
  - [ ] Entities
  - [ ] Components (Partially Done) (PR #76 ...)
  - [ ] Systems
- [ ] Utilities

**Comment by Guerra24** [comment]
I think that doing multiples PR's is the best way. Right now i'm finishing the UI so i need to modify some code but I'm not going to work with the rest of the engine.

**Comment by jlitewski** [comment]
Alright, I'll start working on some of the simpler parts tonight and maybe spend the better chunk of the week rewriting the world, dimension, chunk, and block code, since that's not as easy to abstract in it's current form. Is there a way to get a simple world zip, since I can't for the life of me figure out how to generate a world? Or should I spin up a server locally and connect to that?

**Comment by Guerra24** [comment]
In the latest code I add the world creation screen, use that to generate a world. Edit: Singleplayer -> Create World.

**Comment by jlitewski** [comment]
oh sweet, will do. I'll update my local and get to work then

**Comment by Guerra24** [comment]
And a recommendation, use the client code for abstraction because is more updated than the server ones.

**Comment by jlitewski** [comment]
I'm currently rewriting the ECS system, which is a bit bigger than I thought it was. I am also going to bring in some code from some of my other projects that dealt with the Ashley ECS to help.

**Comment by jlitewski** [comment]
Okay @Guerra24, I'm going to need your input on this. How would you like to store/register/initialize Blocks? I was thinking something along the lines of Minecraft's BlockRegistry with Forge's OreDictionary.

Like, BlockBase.registerBlock("stone", new BlockStone())

I haven't really thought out how to implement this, but it would make things easier down the road if there was a dynamic way to register blocks instead of hardcoding them, you know?

**Comment by Guerra24** [comment]
I already have implemented this time ago but I dropped the system (I don't remember why) but I think that using this with the API will make things easier for modders and everyone who wants to contribute. Edit: To be simple yes.

**Comment by jlitewski** [comment]
Alright. I'm working on the chunk code, so I wanted to try and address this before I got too far into that project.

Speaking of the chunk code, there is a good chance the old chunk format will not work with the new code. I'm going to try and keep it as similar as possible

**Comment by Guerra24** [comment]
I see an error with the removeChunk in the reworked Dimension class, due to the queues are processed in a secondary thread, the chunk's dispose is causing exceptions due to no OpenGL context on that thread and therefore creates a vram memory leak. Edit: to fix this before the rework I made a workaround by marking the chunk unloaded and toRemove, in the render pass unload the 3D model and finally remove it from the Map.

**Comment by jlitewski** [comment]
The Dimension Class in Universal? That shouldn't be in use yet, unless one of the patches I did moving some things to Universal caused it. Anyway I can get a line number so I can add it to the bug I plan to squash with my next round of commits?

**Comment by Guerra24** [comment]
In client's Dimension class. Line 450, the `if(old !=null)` call the removeChunk but this code is running inside the queue thread so when removeChunk calls `chunk.dipose();` starts to throw exceptions.

**Comment by jlitewski** [comment]
ah, alright, I see now. I'll throw a workaround in for now. I'm hoping with the reworked Dimension/World/Chunk/Block classes I can separate the render logic so issues like this don't happen anymore. I'll fix the Kryo issue while I'm at it

**Comment by jlitewski** [comment]
Wouldn't adding chunk.disposeGraphics() before line 265 of Dimension.java fix the issue above?

**Comment by Guerra24** [comment]
No, because removeChunk is called from addChunk when replacing an existing one.

**Comment by jlitewski** [comment]
I'm not sure if you've been watching my fork, but I'm working on the above issue by completely rewriting the multithread code to use Callables and Executors. Hell, I'm rewriting all the code that touches the World class to lay it out better and try to prevent issues like the above from happening again. Which brings me to my current issue of Kyro; is it needed, or can I just directly play with files and bitstreams? I like kyro because it's smart enough to be forward compatible, but holy mother of holy it gets cranky if you don't set things up right.

**Comment by Guerra24** [comment]
Yes, I'm busy but at least see one time by day the fork and looks really good. Yea, the biggest issue of Kryo is that needs an instance per thread and only works in that thread.

**Comment by jlitewski** [comment]
So it might be easier to just drop Kryo and just manually do everything, since having an instance of Kryo on each of the Callable threads would be a huge resource sink. Plus I can document the file structure for modders if needed. Or I can pull my NBT implementation from my game jam entry and we could use that, since there are infinity tools to read that file structure

**Comment by Guerra24** [comment]
Mmm... Let's drop Kryo, if you want pull the NBT implementation, when the PR is ready I will start rewriting the networking (uses Kryonet, like Kryo but for networking). Edit: probably use Netty for this.

**Comment by jlitewski** [comment]
alright. I'll implement it in my rendering refactoring branch and submit a PR with all the changes in that. I'm not sure how much will break with it though, but I haven't really touched any of the current main classes. I'm hoping to finally get that stuff done here soon, but the more I refactor and move things, the more needs to be changed.

Speaking of the renderer, have you looked into Greedy meshing for voxel worlds?

**Comment by Guerra24** [comment]
Read about it but never tested, the Tessellator is very flexible so I think that will be easy to implement. In performance test I did with the Deferred Shading disabled the performance compared with Minecraft is close with more chunks loaded (the old world uses a 3D grid of chunks) and a lot of slow code.

**Comment by jlitewski** [comment]
the way I wrote the new chunk class is it's cut up into slices, and my thought was to only render the slices that can be seen plus the one above/below that one. The data will still be in memory, but it would free up a little bit of render time since it's not rendering the full chunk. and the slices are smart enough to know when they are empty or if they have light data. I still haven't worked out how cross chunk light data will be applied, but hopefully it'll come to me once I start working on the dimension classes.

Speaking of the Tessellator, how flexible is it? is it flexible enough to use VBO's if the client chunk managed it? I saw that you used a VAO and a couple of VBO's, but I really haven't looked into how it works yet because that'll be another can of worms for another day.

**Comment by Guerra24** [comment]
To be simple, the Tessellator is used to create 3D meshes, from a simple cube to practically anything. It provides a simple API to define vertices, normals, texture coords, etc... mimics the old OpenGL 1.1 mesh systems but using modern stuff. By example you can have a big Tessellator per dimension and chunks will share the mesh with others, have one per chunks or per slice, use it to create a character, a tool, etc.

**Comment by jlitewski** [comment]
right, I was just wondering if it would play nicely if it was fed a VBO that chunks managed instead of vertices, but that's just a nit pick from me. Both ways work. I was also thinking of having one Tessellator for the world instance optimized for rendering static objects, like blocks, and one Tessellator optimized for rendering dynamic objects, like entities, would be the best. The static Tessellator wouldn't have to rebuild or modify meshes nearly as often as the dynamic one, so that should free up some render cycles as well

**Comment by Guerra24** [comment]
That might require some changes but nothing complex, just add some stuff when render occurs (load translation, rotation and scale) and allow to change the type of VBO (Static or Dynamic) first one renders faster but updates slower and the other is the inverse.

**Comment by TheOnlySilverClaw** [comment]
Since you're talking about NBT: I've been tinkering around with my own little [mini-serialization library](https://github.com/TheOnlySilverClaw/LightLetter). The next steps would be to optimize the size of "letters" for certain classes and/or make a stream implementation. I'm currently not working on it, since I have no time for coding games right now, but if anyone wants to use it, I could try to add some more features.

**Comment by jlitewski** [comment]
Neat, Thanks for that @TheOnlySilverClaw. It might be better than just pushing data into a stream like I was planning to do.

**Comment by TheOnlySilverClaw** [comment]
Alternatively, you could try [MessagePack](https://github.com/msgpack/msgpack-java) or any of the [Jackson Binary Data Formats](https://github.com/FasterXML/jackson-dataformats-binary), those might be a little more mature and high-level, but might have some overhead.

**Comment by jlitewski** [comment]
MessagePack actually looks really neat. I could see using that for stuff like chunk and network data. Maybe even as a NBT replacement down the line if MessagePack's performance outweighs NBT's massive library of readers and writers

**Comment by Guerra24** [comment]
I decided to rollback the Chunk class to a state before the start of the refactor and now loads and generates the map again, is playable using the old world api.

![javaw_2016-08-30_22-42-13](https://cloud.githubusercontent.com/assets/9023392/18116309/0546c8d6-6f04-11e6-8cfb-5154b4ceba44.png)

**Comment by jlitewski** [comment]
Alright, sweet. Gives me a benchmark to test against with the new code. Might be interesting to see the stats between the two once the rewritten code can run and produce things.

EDIT:
Have you seen this? https://github.com/NovaMods/nova-renderer

**Comment by Guerra24** [comment]
No, but the rendering systems is builded on top of OpenGL 3.3 so its supports modern stuff and works on OS X with no changes.

**Comment by danirod** [comment]
I feel like if I had been alluded or hinted 😅

So I gave a try tonight to the code that is at the moment on HEAD of `develop` branch (7ea337c). MacOS X has always been a pain in the ass for debugging Voxel because OpenGL support is ages behind current standards (_thanks, Apple_) and Intel Iris cards don't help at all (as exposed on screenshots at #33, it glitches even when booting via MS Windows).

As a quick report, at the moment the water implementation looks nice here. Game runs at a slow FPS (probably because it's running on HiDPI mode), but glitches are less visible. Water looks correct here. I only see glitches when looking directly to the ceiling, the screen just becomes noisy like if it was an old TV or something.

<img width="1280" alt="screen shot 2016-08-31 at 22 43 17" src="https://cloud.githubusercontent.com/assets/1568690/18146092/38f6339a-6fce-11e6-90ea-02ac830fb094.png">

I'm running behind the current state of the project, although I keep the project in 'Watching' so I can receive notifications and do some follow up. However, if at some point my laptop comes useful for testing support for things on Intel Iris / MacOS, I can take lots of screenshots 📷📷

**Comment by jlitewski** [comment]
@Guerra24 That link was a minecraft mod rewriting the OpenGl 2.x renderer to a C++ Vulkan renderer. It might be useful to watch it so when we are able to, we can implement Vulkan here (either via LWJGL or a port of the Nova codebase). I'm working on abstracting the rendering code a bit so hopefully it'll be a plug and play solution (plus I need to work on figuring out how the rendering code works so I can start implementing it with the new code).

@danirod nice! My main development computer is running Mac OS X, and one of my main goal is to try and get it running as well as my desktop. That screenshot also looks amazing

**Comment by Guerra24** [comment]
@HACKhalo2 My plan was do it but my graphics card doesn't support Vulkan so I can't test if works.

**Comment by jlitewski** [comment]
Lucky for you, mine does. I guess that'll be my next project after the rewrite

**Comment by jlitewski** [comment]
![screenshot_voxel_1](https://cloud.githubusercontent.com/assets/522065/21847281/08223e18-d7c9-11e6-9582-9e0b5e830613.png)

**Comment by TheOnlySilverClaw** [comment]
Looks nice and I like that you actually dropped Kryo. :)
If I ever have the time in the future, I'd love to mod some stuff into this. :D

**Comment by jlitewski** [comment]
Currently working on getting the ECS system fleshed out and used. It's going to require basically modifying all the existing code that manages the player camera and move it into an Entity and Systems, so things might break for a while here and there as the growing pains happen. However, this will push Voxel one step closer to it's 0.0.10 release, plus it'll rough out the API's needed to enable modders to add their own Entities down the line.

**Comment by Guerra24** [comment]
Status of the new UI system (#90), this are all windows that can be created (to date), it uses a stacking window manager to manage the windows.

![WM](https://puu.sh/tKnCj/b1b67c1b16)
![WM-Inv](https://puu.sh/tKoqf/bfe4bf89f9.png)

**Comment by Guerra24** [comment]
This is the current state of the WM, all major features are implemented.

![img](https://puu.sh/viNxY/631427c1b3.png)

**Comment by Guerra24** [comment]
Some rework in the options area and the window decorations.
![img](https://puu.sh/vrTmE/a4957c2da8.gif)
